### ISSUE TITLE
The mod does not work at all for me

### ISSUE THREAD

**Issue by Tempuser8734** [Odjit/KindredLogistics#5]
I run only KindredLogistics and it's dependencies + ServerLaunchFix. All installed fresh through r2modman.
The game loads in but when I load in to the save there are 2 random results:
1 - ctd with no nottification
2 - game loads and seem to be unmodded, dubble tapping R in inventory does not send items to nearby chests, ".l s" command prints that it does not exist.

```
[Message: Preloader] BepInEx 6.0.0-be.691 - VRising
[Message: Preloader] Built from commit 3ba398f269961fe6721f918423df399d0b481d7e
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2022.3.23f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 3 plugins to load
[Info   :   BepInEx] Loading [ServerLaunchFix 0.2.0]
[Info   :   BepInEx] Loading [VampireCommandFramework 0.9.0]
[Message:VampireCommandFramework] Note: Vampire Command Framework is loading on the client but only adds functionality on the server at this time, seeing this message is not a problem or bug.
[Info   :   BepInEx] Loading [KindredLogistics 1.0.2]
[Info   :KindredLogistics] Plugin KindredLogistics version 1.0.2 is loaded!
[Message:   BepInEx] Chainloader startup complete
```

**Comment by Odjit** [comment]
If you are seeing "does not exist" then you are entering the mod's commands into console. Mod commands are entered in the chat box, not console.
Only adminauth and other native V rising commands go in console. 
VCF and Logistics go into chat.

Tapping the R while hovering over your inventory will only work if you enable it, through `.l ss` as you need to turn on sort stash capabilities. (some people dislike the sorting part, but since we're piggybacking on it, not much to do). Otherwise .stash will always work.

**Comment by Tempuser8734** [comment]
Thank you. Everything is as you described and work very well.
It seems the only problem was me being to stupid to figure out where the commands should go.
